project:
  type: book
  output-dir: book
  resources:
    - /.nojekyll

book:
  title: "TBEP-CC"
  subtitle: "Tampa Bay Estuary Program: Climate Change Indicators"
  author:
  - name: Benjamin D. Best
    orcid: 0000-0002-2686-0784
    email: ben@ecoquants.com
    affiliations:
      - name: EcoQuants LLC
        address: 211 W Gutierrez St, Unit 12
        city: Santa Barbara
        state: CA
        postal-code: 93101
  - name: Marcus W. Beck
    orcid: 0000-0002-4996-0059
    email: mbeck@tbep.org
    affiliations:
      - name: Tampa Bay Estuary Program
        address: 263 13th Ave South
        city: St. Petersburg
        state: FL
        postal-code: 33701
  repo-url: https://github.com/tbep-tech/climate-change-indicators
  reader-mode: true
  repo-actions: [edit]
  downloads: [pdf, docx]
  sharing: [twitter, facebook]
  search: true
  date: today
  date-format: "YYYY-MM-DD"
  page-navigation: true
  page-footer:
    left: |
      © <a href="https://tbep.org"  target="_blank">Tampa Bay Estuary Program</a>
    right: |
      Built with <a href="https://quarto.org/" target="_blank">Quarto</a>
  chapters:
    - index.qmd
    - intro.qmd
    - data.qmd
    - references.qmd

bibliography: references.bib

lightbox: true

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    mermaid:
      theme: neutral
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt
  docx: default

editor: visual

editor_options:
  chunk_output_type: console


